const DEMO_PROJECT_ID = "project-pole-90000";

export const INSTALLATION_DEMO_DATA = {
  projects: [
    {
      id: DEMO_PROJECT_ID,
      name: "โครงการติดตั้งเสาไฟ 90,000 ต้น",
      code: "POLE-90000",
      status: "active",
    },
  ],
  profiles: [
    { id: "profile-prasit", full_name: "ประสิทธิ์ ศรีสุข", role: "member" },
    { id: "profile-somchai", full_name: "สมชาย ใจดี", role: "member" },
  ],
  teams: [
    {
      id: "team-alpha",
      project_id: DEMO_PROJECT_ID,
      name: "ทีมติดตั้ง A",
      team_type: "installation",
      leader_profile_id: "profile-prasit",
      leader_name: "ประสิทธิ์ ศรีสุข",
      crew_size: 8,
      assigned_work: "ติดตั้งเสาและบันทึกความคืบหน้ารายวัน",
      is_active: true,
    },
    {
      id: "team-bravo",
      project_id: DEMO_PROJECT_ID,
      name: "ทีมฐานราก B",
      team_type: "foundation",
      leader_profile_id: "profile-somchai",
      leader_name: "สมชาย ใจดี",
      crew_size: 6,
      assigned_work: "เตรียมฐานรากและตรวจสอบแนวเจาะ",
      is_active: true,
    },
  ],
  plans: [
    {
      id: "plan-sisaket-w1",
      project_id: DEMO_PROJECT_ID,
      name: "แผนติดตั้งศรีสะเกษ สัปดาห์ที่ 1",
      area_name: "คลัสเตอร์เมืองศรีสะเกษ",
      province: "ศรีสะเกษ",
      start_date: "2026-06-22",
      end_date: "2026-06-28",
      status: "in_progress",
      notes: "เร่งแนวถนนหลักก่อนเข้าสู่พื้นที่ชุมชน",
    },
    {
      id: "plan-korat-w1",
      project_id: DEMO_PROJECT_ID,
      name: "แผนติดตั้งนครราชสีมา สัปดาห์ที่ 1",
      area_name: "คลัสเตอร์โคราชเหนือ",
      province: "นครราชสีมา",
      start_date: "2026-06-29",
      end_date: "2026-07-05",
      status: "ready",
      notes: "ประสานรถขนส่งเข้าพื้นที่ก่อน 08:00 น.",
    },
  ],
  points: [
    {
      id: "point-sk-001",
      plan_id: "plan-sisaket-w1",
      project_id: DEMO_PROJECT_ID,
      team_id: "team-alpha",
      point_code: "SK-A-001",
      name: "จุดติดตั้งบ้านหนองครก",
      location_text: "บ้านหนองครก ตำบลโพธิ์ ใกล้วัดประจำหมู่บ้าน",
      province: "ศรีสะเกษ",
      district: "เมืองศรีสะเกษ",
      subdistrict: "โพธิ์",
      latitude: 15.1201,
      longitude: 104.3299,
      assigned_date: "2026-06-22",
      target_units: 12,
      assigned_work: "ติดตั้งเสาแนวถนนหลักและส่งรายงานภาพถ่ายสิ้นวัน",
      status: "in_progress",
    },
    {
      id: "point-sk-002",
      plan_id: "plan-sisaket-w1",
      project_id: DEMO_PROJECT_ID,
      team_id: "team-bravo",
      point_code: "SK-B-002",
      name: "จุดฐานรากแยกโพธิ์",
      location_text: "สี่แยกทางเข้าตำบลโพธิ์",
      province: "ศรีสะเกษ",
      district: "เมืองศรีสะเกษ",
      subdistrict: "โพธิ์",
      latitude: 15.1085,
      longitude: 104.3422,
      assigned_date: "2026-06-23",
      target_units: 8,
      assigned_work: "เจาะฐานราก ตรวจระดับ และส่งผลตรวจรับ",
      status: "assigned",
    },
    {
      id: "point-nm-001",
      plan_id: "plan-korat-w1",
      project_id: DEMO_PROJECT_ID,
      team_id: "team-alpha",
      point_code: "NM-A-001",
      name: "จุดติดตั้งโนนสูง",
      location_text: "ถนนสายหลัก อำเภอโนนสูง",
      province: "นครราชสีมา",
      district: "โนนสูง",
      subdistrict: "โนนสูง",
      latitude: 15.1804,
      longitude: 102.2547,
      assigned_date: "2026-06-30",
      target_units: 16,
      assigned_work: "ติดตั้งเสาและตรวจความปลอดภัยแนวสาย",
      status: "planned",
    },
  ],
};

