export const DEFAULT_PROJECT_TEMPLATES = [
  {
    id: "template-pole-13602",
    name: "13,602 Pole Program",
    unitLabel: "poles",
    targetUnits: 13602,
    targetProfitThb: 0,
    targetMarginPct: 0,
    targetNpvThb: 0,
    targetIrrPct: 37.8,
    targetMirrPct: 24,
    targetPaybackDays: 14,
    machineryBudgetThb: 98000,
    targetIrr: 37.8,
    targetMirr: 24,
  },
  {
    id: "template-pole-90000",
    name: "90,000 Pole Program",
    unitLabel: "poles",
    targetUnits: 90000,
    targetProfitThb: 0,
    targetMarginPct: 0,
    targetNpvThb: 0,
    targetIrrPct: 37.8,
    targetMirrPct: 24,
    targetPaybackDays: 14,
    machineryBudgetThb: 650000,
    targetIrr: 37.8,
    targetMirr: 24,
  },
];
